### ISSUE TITLE
ReferenceError: primordials is not defined

### ISSUE THREAD

**Issue by shiyuanzheng** [imageslr/weapp-library#11]
运行本地 Mock Server跑不起来， gulp mock报错

$ gulp --version
CLI version: 2.3.0
Local version: 3.9.1

$ node -v
v14.15.4

**Comment by imageslr** [comment]
请尝试使用 nvm 安装 nodejs v10.10.0。nvm 不会污染你现在的 node 环境，并且不同版本间切换也很方便。

你这个报错应该是 node 版本太高了。。

**Comment by shiyuanzheng** [comment]
降低版本就可以了，多谢
