### ISSUE TITLE
请问有没有后台管理界面的截图？

### ISSUE THREAD

**Issue by redcat789** [imageslr/weapp-library#2]
如题

**Comment by imageslr** [comment]
文档里应该有一些截图。后台分为图书馆的管理后台，包括订单查看和图书登记；以及超级管理员的管理沟通，包括图书馆、用户信息的管理和图书信息的管理。其实都是简单的数据库控制，没有特别的。

**Comment by redcat789** [comment]
了解了，谢谢！
