### ISSUE TITLE
想知道数据库脚本

### ISSUE THREAD

**Issue by tangmingze7280** [imageslr/weapp-library#3]
您好，我想获取一下数据库脚本和图片数据资源 。 寻找了好久

**Comment by imageslr** [comment]
抱歉，爬虫脚本是当时另一个同学写的，现在已经用不了了。这个数据在腾讯云服务器上，但是服务器到期了就没续费。

**Comment by tangmingze7280** [comment]
我好想给你续费啊


17853537280@163.com
 
发件人： Zhu
发送时间： 2019-03-26 17:11
收件人： imageslr/weapp-library
抄送： tangmingze7280; Author
主题： Re: [imageslr/weapp-library] 想知道数据库脚本 (#3)
抱歉，爬虫脚本是当时另一个同学写的，现在已经用不了了。这个数据在腾讯云服务器上，但是服务器到期了就没续费。
―

**Comment by imageslr** [comment]
我们爬到的图书数据其实并不多，按照分类号爬的，基本全是马克思恩格斯著作、毛邓选集、哲学、教育类的书。如果你是想做演示的话，自己模拟几个数据完全够用。如果你想获取完整图书数据库商用的话，我感觉这个爬虫方法还是行不通的。

**Comment by tangmingze7280** [comment]
谢谢，哥



17853537280@163.com
 
发件人： Zhu
发送时间： 2019-03-26 21:09
收件人： imageslr/weapp-library
抄送： tangmingze7280; Author
主题： Re: [imageslr/weapp-library] 想知道数据库脚本 (#3)
我们爬到的图书数据其实并不多，按照分类号爬的，基本全是马克思恩格斯著作、毛邓选集、哲学、教育类的书。如果你是想做演示的话，自己模拟几个数据完全够用。如果你想获取完整图书数据库商用的话，我感觉这个爬虫方法还是行不通的。
