### ISSUE TITLE
请问您的项目的api接口都无法使用了吗？

### ISSUE THREAD

**Issue by SZ98** [imageslr/weapp-library#6]

**Comment by imageslr** [comment]
您好，我的项目现在是没有后端的，都是使用模拟数据。模拟数据放在 [easy-mock](https://easy-mock.com/project/5aacc9a1d3f6bd35dfb4be65) 上。

看了一下是因为 easy-mock 网站的 https 证书没了，这个网站间歇性的会挂掉。你可以拉下代码，在本地跑起来。开发工具里是可以关闭 https 校验的

**Comment by imageslr** [comment]
[Easy-Mock-API.zip](https://github.com/imageslr/weapp-library/files/3849673/Easy-Mock-API.zip)

这是打包下载的 easy-mock 的 API

**Comment by SZ98** [comment]
好的，十分感谢
