### ISSUE TITLE
小程序卡在注册登录页面

### ISSUE THREAD

**Issue by CedrusZhao** [imageslr/weapp-library#7]
扫码进入小程序后，无法注册登陆，一直卡着。

**Comment by imageslr** [comment]
你好现在线上的小程序是依赖 EasyMock 提供的 mock 服务。但是这个平台的 https 证书挂了。建议下载源码本地编译

**Comment by CedrusZhao** [comment]
我想把这个小程序改造一下，让大家下载后可以直接运行。你觉得呢？

**Comment by imageslr** [comment]
@CedrusZhao 你好，已经改完了，请尝试一下
