### ISSUE TITLE
mocks文件夹怎么能导入本地的easy-mock里去呢？

### ISSUE THREAD

**Issue by james6176** [imageslr/weapp-library#8]

**Comment by imageslr** [comment]
这确实是一个问题，我研究下。发一个打包好的 docker 如何？

**Comment by imageslr** [comment]
@james6176 你好，我已经添加了所有 API 接口的 mock 服务，请参考 README 启动。即刻上手体验，比 easy-mock 简单。

如果小程序弹出 toask，报错“发生未知错误”，这说明某个接口的配置有问题，请在这里评论：

1.  所处的页面
2. 进行的操作

**Comment by james6176** [comment]
调通了，非常感谢！
